services:
  backend:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    container_name: ft_transcendence_backend
    ports:
      - "3000:3000"
    env_file:
      - ./apps/server/.env
    environment:
      NODE_ENV: ${NODE_ENV:-production}
    volumes:
      - backend_data:/app/db/data
    networks:
      - ft_transcendence
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/healthz', (r) => { process.exit(r.statusCode === 200 ? 0 : 1); })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-/api}
    container_name: ft_transcendence_frontend
    ports:
      - "8443:8443"
      - "8080:8080"
    volumes:
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - ft_transcendence
    restart: unless-stopped

networks:
  ft_transcendence:
    driver: bridge

volumes:
  backend_data:
